version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
        depends_on:
            - php
            - mysqldb
    php:
        image: redegalsys/php70fpm
        restart: always
        volumes:
            - "./web:/var/www/html"
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    mysqldb:
        image: mysql:5.7.22
        container_name: mysqlsrv_1742
#        command: --innodb_use_native_aio=0
        command: --sql_mode=""
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "13306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
